version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017  

volumes:
  db-data:
  mongo-config: